---
- ec2:
    key_name: '{{ key_name_aws }}'
    group: '{{ sec_group }}'
    instance_type: '{{ inst_type }}'
    image: '{{ ami_id }}'
    region: '{{ region }}'
    vpc_subnet_id: '{{ subnet_id }}'
    wait : yes
    count: '{{ count }}'
    assign_public_ip : '{{ public_ip }}'
    volumes:
      - device_name: /dev/xvda
        device_type: gp2
        volume_size: 10
        delete_on_termination: true
      - device_name: /dev/xvdb
        device_type: gp2
        volume_size: 20
        delete_on_termination: true
  register: ec2

- ec2_tag: resource={{ item.id }} region={{ region }}
  args:
    tags: { Name: '{{ instance_name }}', Env: '{{ tag_env }}', Ansible: "Yes", Type: '{{ tag_type }}', Product: '{{ tag_product }}'}
  with_items: ec2.instances

- add_host:
    hostname: "{{ instance_name }}"
    name: "{{ instance_name }}"
    ansible_ssh_host: "{{ item.public_ip }}"
    ec2_tag_Name: "{{ instance_name }}"
    ip_private: "{{ item.private_ip }}"
    groups: "{{ hosts_groups }}"
  with_items: ec2.instances

- wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=320 state=started
  with_items: ec2.instances
