---
- hosts: localhost
  vars:
    instance_name: app.{{ domain }}
    hosts_groups: twitter-check
    flavor_name: 'micro.2GB'
    security_groups: twitter-app
  roles:
    - cloud-instance

- hosts: localhost
  vars:
    instance_name: mon.{{ domain }}
    hosts_groups: twitter-check
    flavor_name: 'medium.8GB'
    security_groups: twitter-app
  roles:
    - cloud-instance
